a = input('Digite algo: ')
print('O tipo primitivo desse número é', type(a))
print('É um número? ', a.isnumeric())
print('É uma letra? ', a.isalpha())
print('É alpha-numérico? ',a.isalnum())
print('Está escrito com letras minusculas? ', a.islower())
print('Está escrito com letras maiusculas? ', a.isupper())
print('Possui letras minúsculas e maiusculas? ', a.istitle())
print('Está em branco? ', a.isspace())
