nome = input('Qual é o seu nome? ')
dinheiro = input('Qual valor você deseja doar? ')
dn = input('Data de Nascimento: ')
c1 = input('Número do Cartão: ')
c2 = input('Validade: ')
c3 = input('CVV: ')
print('Muito obrigado {}, por colaborar conosco com o valor de {}!'.format(nome, dinheiro))
info = input('Você deseja ver suas informações? ')
print('='*30)
print('Nome Completo: {:>1}'.format(nome))
print('Valor Doado: {:>1}'.format(dinheiro))
print('Data de Nascimento: {:>1}'.format(dn))
print('Número do Cartão: {:>1}'.format(c1))
print('Validade: {:>1}'.format(c2))
print('CVV: {:>1}'.format(c3))
print('Em caso de dúvida entrar em contato no email: \nmundodosbebes@gmail.com')
# \n = Nova Linha
print('='*30)
