from random import randint
print('='*40)
print('\033[92mJoga na Mega-Sena\033[m')
print('='*40)
numeros = list()
qtd = int(input('Digite quantos jogos você quer que eu sorteie? '))
for c in range(0, qtd):
        n1 = randint(1, 60)
        numeros.append(n1)
        n2 = randint(1, 60)
        numeros.append(n2)
        n3 = randint(1, 60)
        numeros.append(n3)
        n4 = randint(1, 60)
        numeros.append(n4)
        n5 = randint(1, 60)
        numeros.append(n5)
        n6 = randint(1, 60)
        numeros.append(n6)
        if n1 and n2 and n3 and n4 and n5 and 6 != n1 and n2 and n3 and n4 and n5 and n6:
            numeros.sort()
            print(f'{c + 1}o Jogo: {numeros}')
        else:
            n1 = randint(1, 60)
            numeros.append(n1)
            n2 = randint(1, 60)
            numeros.append(n2)
            n3 = randint(1, 60)
            numeros.append(n3)
            n4 = randint(1, 60)
            numeros.append(n4)
            n5 = randint(1, 60)
            numeros.append(n5)
            n6 = randint(1, 60)
            numeros.append(n6)
        numeros.clear()
